name: flutter_app_hackaton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.0
  cloud_firestore: ^1.0.0
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  numberpicker: ^2.1.1
  flutter_picker: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lottie: ^1.3.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/lottie/
    - assets/images/icons/

  fonts:
    # Add fontss from the fonts directory to the application.
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
          weight: 700